Albrecht Durer: 0
Boris Kustodiev: 1
Camille Pissarro: 2
Claude Monet: 3
Giovanni Battista Piranesi: 4
Gustave Dore: 5
Ilya Repin: 6
Ivan Aivazovsky: 7
Ivan Shishkin: 8
John Singer Sargent: 9
Marc Chagall: 10
Martiros Saryan: 11
Pablo Picasso: 12
Paul Cezanne: 13
Paul Gauguin: 14
Pierre-Auguste Renoir: 15
Pyotr Konchalovsky: 16
Raphael Kirchner: 17
Rembrandt: 18
Zdislav Beksinski: 19
 