MODELS:
  # BACKBONE:
    # FREEZE_AT: 0  # 1 means freezing the stem, 2 means stem + first stage and so on
  RESNET:
    STEM_OUT_CHANNELS: 64
    RES2_OUT_CHANNELS: 64  # output channels from first stage
    DEPTH: 18
    OUT_FEATURES: ['linear']  # output of first stage is called res2
  FPN:
    IN_FEATURES: ['linear']
    OUT_CHANNELS: 128
  BRANCH:
    BRANCH_TYPE:
      'linear'  # 'fpn' or 'linear'
    BRANCHES:
      ARTISTS:
        NUM_CLASSES: 20
      GENRES:
        NUM_CLASSES: 10
      STYLES:
        NUM_CLASSES: 20
DATA:
  BATCH_SIZE:
    ARTISTS: 16
    GENRES: 32
    STYLES: 32
TRAINING:
  # RESUME_WEIGHTS: /content/drive/MyDrive/artinspector/weights/epoch0.pt  # used for training
  RESUME_WEIGHTS: /home/amar/dev/projects/major_project/art_inspector/models/epoch10.pt  # used for testing
