MODELS:
  # BACKBONE:
    # FREEZE_AT: 0  # 1 means freezing the stem, 2 means stem + first stage and so on
  RESNET:
    STEM_OUT_CHANNELS: 64
    RES2_OUT_CHANNELS: 64  # output channels from first stage
    DEPTH: 18
    OUT_FEATURES: ['res5']  # output of first stage is called res2
  FPN:
    IN_FEATURES: ['res5']
    OUT_CHANNELS: 128
  BRANCH:
    BRANCH_TYPE:
      'fpn'  # 'fpn' or 'linear'
    BRANCHES:
      ARTISTS:
        NUM_CLASSES: 20
      GENRES:
        NUM_CLASSES: 10
      STYLES:
        NUM_CLASSES: 20
DATA:
  BATCH_SIZE:
    ARTISTS: 16
    GENRES: 32
    STYLES: 32
